language:
  - java
  - node_js

jdk:
  - openjdk8
  - oraclejdk8

node_js: stable

branches:
  only:
    - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "han-feng-github"
    token:
      secure: $SONAR_CLOUD_TOKEN

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "cvicse-frontend/node_modules"

script:
  - mvn clean package

after_success:
  - mvn jacoco:report coveralls:report
  - sonar-scanner
  - bash <(curl -s https://codecov.io/bash)
