language:
  - java
  - node_js

jdk:
  - openjdk8
  - oraclejdk8

node_js: stable

branches:
  only:
    - master

notifications:
  email: false

addons:
  sonarcloud:
    organization: "han-feng-github"
    token:
      secure: $SONAR_CLOUD_TOKEN

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
    - "cvicse-frontend/node_modules"

script:
  - mvn clean package

after_success:
  - mvn coveralls:report
  - bash <(curl -s https://codecov.io/bash)
  - sonar-scanner

deploy:
  provider: pages
  local-dir: cvicse-frontend/target/dist
  skip-cleanup: false
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
